export const CST = {
    SCENE: {
        LOAD_SCENE: "Load",
        MENU_SCENE: "Menu",
        NAME_SCENE: "NameScene",
        CHARACTER_SELECTION_SCENE: "CharacterSelection",
        DRESS_UP_SCENE: "DressUpScene",
        BUILDING_SCENE: "BuildingScene",
        DIALOG_BOX: "DialogBoxScene",
        LEVEL1_OFFICE_SCENE: "Level1OfficeScene",
        LEVEL1_DUNGEON_SCENE: "Level1DungeonScene",
        LEVEL1_DUNGEON_GEM_SCENE: "Level1DungeonGemScene",
        LEVEL1_DUNGEON_POND_SCENE: "Level1DungeonPondScene",
        LEVEL1_DUNGEON_RIVER_SCENE: "Level1DungeonRiverScene",
        LEVEL1_DUNGEON_HAT_PUZZLE_SCENE: "Level1DungeonHatPuzzleScene",
        LEVEL1_DUNGEON_BOOT_PUZZLE_SCENE: "Level1DungeonBootPuzzleScene",
        LEVEL1_EXCAVATION_SCENE: "Level1ExcavationScene",
        LEVEL1_EYEWEAR_SCENE:"Level1EyewearScene",
        TRAFFIC_PUZZLE_SCENE:"TrafficPuzzleScene",
        BUY_SCENE:"BuyScene",
        LEVEL1_WHITELINING_SCENE:"Whitelining",
        UI_SCENE: "UIScene",
        BUILD_SCENE:"BuildScene",
        FLAGS_BUILD_SCENE:"FlagsBuildScene",
        SKATEPARK_BUILD_SCENE:"SkateParkBuildScene"
    },
    COMMON_IMAGES: {
        INPUT_BOX: "InputBox.png",
        HEADER_BOX: "HeaderBox.png",
        SELECTED_POPUP_GLOW: "SelectedPopupGlow.png",
        DIALOG_BOX: "dialoguebox.png",
        DIALOG_LABLE: "dialog_lable.png",
        SCROLLABLE_PANEL_BG: "ScrollablePanelBG.png",
        SCROLL_BAR: "Scroll_bar.png",
        SCROLL: "Scroll.png",
        Map: "Map.png",
        BG: "BG.png",
        BG_OVERLAY: "BG_OL.png",
        FULL_SCREEN_BUTTON: "full-screen.png",
        BLACK_OVERLAY :"blackLayer.png",
        BUILD:"build-icon.png"
    },
    PROLOGUE: {
        Base1: "base-1.png",
        Base2: "base-2.png",
        Base3: "base-3.png",
        Bench: "bench.png",
        BenchShadow: "bench-shadow.png",
        Bridge: "bridge.png",
        BridgeFront: "bridge-front.png",
        BridgeShadow: "bridge-shadow.png",
        BurgerBalloon: "burger-balloon.png",
        BurgerBalloon1: "burger-balloon-1.png",
        BurgerBalloon2: "burger-balloon-2.png",
        BurgerBase: "burger-base.png",
        BurgerBoard: "burger-board.png",
        BurgerChair1: "burger-chair-1.png",
        BurgerChair2: "burger-chair-2.png",
        BurgerChair3: "burger-chair-3.png",
        BurgerChair4: "burger-chair-4.png",
        BurgerFrontpole: "burger-frontpole.png",
        BurgerNameBoard: "burger-name.png",
        CABarrel: "ca-barrel.png",
        CABricks2: "ca-bricks -2.png",
        CABricks: "ca-Bricks.png",
        CABrickSingle: "ca-brick-single.png",
        CABrickSingle2: "ca-brick-single-2.png",
        CACart: "ca-cart.png",
        CACementMixer: "ca-cement Mixer.png",
        CACement: "ca-cement.png",
        CADustbin: "ca-dustbin.png",
        CAHouseInprogress: "ca-house in progress.png",
        CALadder: "ca-ladder 1.png",
        CALadder2: "ca-ladder 2.png",
        CAPipes: "ca-pipes.png",
        CAPit2: "ca-pit 2.png",
        CAPit: "ca-pit-1.png",
        CASand: "ca-sand.png",
        CASandHeap: "ca-sand-heap.png",
        CASeparator: "ca-separator.png",
        CASeparator2: "ca-separator-2.png",
        CASeparator3: "ca-separator-3.png",
        CAShovel: "ca-shovel.png",
        CASign: "ca-sign.png",
        VASign1: "ca-sign 1.png",
        CASteelBlocks: "ca-steel-blocks.png",
        CAStone1: "ca-stone-1.png",
        CAStone2: "ca-stone-2.png",
        CAStone3: "ca-stone-3.png",
        CAWoodpanels: "ca-wood-panels.png",
        CABoard: "board.png",
        CABoundary: "boundary.png",
        CAcementpurple: "cement-purple.png",
        ChineseRestaurantSitout: "chinese_restaurant_sitout.png",
        Dustbin: "dustbin.png",
        DustbinShadow: "dustbin_shadow.png",
        FountaintSitout: "founatain-and-sit-out.png",
        Founatain: "fountain.png",
        FountainBench: "fountain-bench.png",
        FountainBenchShadow: "fountain-bench-shadow.png",
        GardenSitout: "garden-sitout.png",
        GlassBuilding: "glass-building.png",
        HomeScreenBase: "homescreen-base.png",
        HospitalSitout: "hospital-and-sit out.png",
        HouseBase: "house-base.png",
        HouseBuilding: "house-building.png",
        IceCreamBuilding: "icecream-building.png",
        ParkAsset1: "park-asset-1.png",
        ParkAsset2: "park-asset-2.png",
        ParkAsset3: "park-asset-3.png",
        Parking: "parking.png",
        ParkLight: "park-light.png",
        PetStore: "pet-store.png",
        Restaurant: "restaurant.png",
        SideGlassBuilding: "side-glass-building.png",
        SmallBridge: "small-bridge.png",
        SmallBridgeFront: "small-bridge-front.png",
        Stool: "stool.png",
        StoolShadow: "stool-shadow.png",
        Soil1: "soil-1.png",
        Soil2: "soil-2.png",
        Soil3: "soil-3.png",
        Cycle1: "cycle-1.png",
        Cycle2: "cycle-2.png",
        Cycle3: "cycle-3.png",
        Cycle4: "cycle-4.png",
        WaterFountain: "water-fountain.png",
        PopcornStand: "popcorn-stand.png",
        Pots: "pots.png",
        //Map: "Map.png",
        Arrow: "arrow.png",
    },
    LEVEL1_OFFICE: {
        MAIN_FLOOR: "main-floor.png",
        OPEN_GROUND: "open-ground.png",
        CONFERENCE_ROOM: "conference-room-with-walls.png",
        BIG_TABLE: "big-table.png",
        BOOK_SELF: "book-shelf.png",
        SMALL_TABLE: "small-table.png",
        TABLE_UPPER_CORNER: "table-upper-corner.png",
        INNER_OFFICE_FLOOR: "inner-office-floor.png",
        INNER_OFFICE_TABLE: "inner-office-table.png",
        INNER_OFFICE_DUSTBIN: "inner-office-dustbin.png",
        OFFICE_HARD_HAT: "inner-office-hard-hat.png",
        SIDE_CHAIR: "chair.png",
        INNER_OFFICE_ROUND_TABLE: "inner-office-roundtable.png",
        SOFA_BACK: "sofa-back.png",
        SOFA_FRONT: "sofa-front.png",
        ROUND_TABLE: "round-table-ig.png",
        MAIN_TABLE: "main-table.png",
        WEIRD_TABLE: "table-2.png",
        ROUND_SEAT: "round-seat.png",
        CARPET: "carpet.png",
        MAIN_CHAIR: "main-chair.png",
        STAIRCASE: "stairs.png",
        DUNGEON_OPENING: "Opening-to-dungeon.png",
        LADDER: "Ladder.png",
        ARROW:"arrowGreenOffice.png",
	},
    LEVEL1_DUNGEON: {
        GROUND: "ground-new.png",
        BOXES: "boxes.png",
        CART: "cart.png",
        CAVETRACK: "cave-and-track.png",
        DIRTWHEEL: "dirt-wheel.png",
        HOLE1: "hole-1.png",
        HOLE2: "hole-2.png",
        HOLE3: "hole-3.png",
        PEBBLES: "pebble.png",
        STONE: "stone.png",
        STONE_1: "stone-1.png",
        STONE_2: "stone-2.png",
        STONE_3: "stone-3.png",
        STONE_4: "stone-4.png",
        TRACK2: "track-2.png",
        WOODENPLANK: "wooden-plank.png",
        WOODENSTAIR: "wooden-stair.png",
        LADDER_LIGHT:"ladder-light.png",
        PIPES:"pipes.png",
        STAND:"stand.png"
    },
    LEVEL1_DUNGEON_GEM: {
        GROUND: "ground.png",
        BOXES: "box-cluster.png",
        BOX: "box.png",
        BIG_CART: "big-cart.png",
        CART: "cart.png",
        BRIDGE: "bridge.png",
        CAVES: "caves.png",
        CLOSED_CHEST: "closed-chest.png",
        CLOSED_CHEST_PURPLE: "closed-chest-1.png",
        OPEN_CHEST: "open-chest.png",
        OPEN_CHEST_JEWEL: "open-chest-jewel.png",
        HOLE: "hole.png",
        HOLE1: "hole-1.png",
        STONE: "stone.png",
        STONE_1: "stone-1.png",
        STONE_2: "stone-2.png",
        STONE_3: "stone-3.png",
        STONE_4: "stone-4.png",
        STONE_5: "stone-5.png",
        STONE_6: "stone-6.png",
        STONE_SET: "stone-set.png",
        TEMPLE: "temple.png",
        DRUMS: "drums.png",
        DRUM_SINGLE: "drum-single.png"
    },
    LEVEL1_DUNGEON_POND: {
        GROUND: "ground.png",
        CAVE:"cave.png",
        BLACK_LAYER:"black-layer.png",
        CLUSTER1:"cluster 1.png",
        CLUSTER2:"cluster-2.png",
        LIGHTSOURCE:"light-source.png"
    
    },
     LEVEL1_DUNGEON_RIVER: {
        GROUND: "ground.png",
        FLOATING_ROCKS:"floating-rocks.png",
        LILY:"lily.png",
        LILYADS1:"lilyads-1.png",
        LILYADS2:"lilyads-2.png",
        LILYADS4:"lilyads-4.png",
        LILYADS5:"lilyads-5.png",
        ROCK1:"rock1.png",
        ROCK2:"rock2.png",
        ROCK3:"rock3.png",
        ROCK4:"rock4.png",
        ROCK5:"rock5.png",
    
    },
    LEVEL1_DUNGEON_HAT_PUZZLE: {
        GROUND: "ground.png",
        LEVER:"lever.png",
        LEVER_SHADOW:"lever-shadow.png",
        ARROW:"arrowGreenHat.png",
        BARRICADE:"barricade.png",
        BOX:"box.png",
        BOXES:"boxes.png",
        CART:"cart.png",
        CART_1:"cart-1.png",
        QUESTION_MARK:"Hat_level_questionmark.png",
        HAT1:"Hat-1.png",
        HAT2:"Hat-2.png",
        HAT3:"Hat-3.png",
        HAT4:"Hat-4.png",
        OPTION_HAT_1:"Option-hat-1.png",
        OPTION_HAT_2:"Option-hat-2.png",
        OPTION_HAT_3:"Option-hat-3.png",
        OPTION_HAT_4:"Option-hat-4.png",
        OPTION_HAT_5:"Option-hat-5.png",
        OPTION_HAT_6:"Option-hat-6.png",
        HATS_SHADOW:"hats-shadow.png",
        LAYER1:"Layer 1.png",
        LEVER_MACHINE:"lever-machine.png",
        TRACKS:"tracks.png",
        STOP_BARRICADE:"stop-barricade.png",
        STONE1:"stone-1.png",
        STONE2:"stone-2.png",
        STONE3:"stone-3.png",
        STONE4:"stone-4.png",
        STONE5:"stone-5.png",
        STONE6:"stone-6.png",
        BOX_GROUP_1:"box group 1.png",
        BOX_GROUP_2:"box group 2.png",
        BOX_GROUP_3:"box group 3.png",
        BOX_GROUP_4:"box group 4.png",
        STONES:"stones.png",
        STONES_DUNGEON:"stonesDungeon.png",
        SMALL_CART:"small-cart.png",
        OPEN_CHEST_JEWEL:"open-chest-jewel.png",
        BUBBLE:"bubble.png",
        FILED_CART:"filled-cart.png"
    },
    LEVEL1_DUNGEON_BOOT_PUZZLE: {
        GROUND:"ground (2).png",
        DEBRIS:"debris.png",
        LADDER:"wooden-stair.png",
        ARROW:"arrowGreenBoot.png",
        BIG_PLATFORM:"big-platform.png",
        SMALL_PLATFORM:"small-platform.png",
        BOOT_PLATFORM:"boot-platform.png",
        STONE_CLUSTER:"stone-cluster.png",
        CART:"cart.png",
        WOODEN_BORDER:"wooden-bordder 1.png",
        WOODEN_BORDER2:"wooden-bordder.png",
        WOODEN_PLANK:"wooden-plank (1).png",
        WOOD_TRUNK:"wood-trunk.png",
        BOX:"box.png",
        LADDER_LIGHT:"ladder-light.png",
        STONE_PATH1:"stone-path 1.png",
        STONE_PATH2:"stone-path.png",
        STONE_PATH3:"stone-path 3.png",
        STONE_1:"stone-1.png",
        STONE_2:"stone-2.png",
        CLOSED_CHEST:"closed-chest-1.png",
        BROKEN_LADDER:"broken-stair.png",
        BOOT_LADDER:"boot-ladder.png"
    },
  
    LEVEL1_EXCAVATION: {
        GROUND:"ground.png",
        BRICK:"3.png",
        DEBRIS1:"debris 1.png",
        DEBRIS2:"debris 2.png",
        DEBRIS3:"debris 3.png",
        DEBRIS4:"debris 4.png",
        DEBRIS5:"debris 5.png",
        EXCAVATOR:"excavator.png",
        "1":"1.png",
        "2":"2.png",
        "3":"3.png",
        "4":"4.png",
        "5":"5.png",
        "6":"6.png",
        "7":"7.png",
        "8":"8.png",
        "9":"9.png",
        "10":"10.png",
        "11":"11.png",
        "12":"12.png",
        "20":"20.png",
        LADDER:"Ladder.png",
        OPENING:"Opening-to-dungeon.png",
        MOP:"Mop.png",
        MOP_SHADOW:"mop shadow.png",
        EXCAVATOR_PART_1:"excavator-part-1.png",
        EXCAVATOR_PART_2:"excavator-part-2.png",
        EXCAVATOR_PART_3:"excavator-part-3.png",
    },
    LEVEL1_EYEWEAR: {
        GROUND:"ground.png",
        BLACK_CAR:"big-car.png",
        YELLOW_CAR:"back-car-1.png",
        LONG_TRUCK:"long-truck.png",
        RED_CAR:"back-car-2.png",
        LAMP:"streelight.png",
        BUSH:"bush.png",
        POT:"pot.png",
        POT1:"pot-1.png",
        RECTANGLE_BUSH:"rectangle-bush.png",
        SHOP:"shop.png",
        SHOP_BORDER:"shop-border.png",
        TABLE1:"table-1.png",
        TABLE2:"table-2.png",
        TREE:"tree.png",
        TREE_BASE1:"tree-base1.png",
        TREE_BASE2:"tree-base2.png",
        STORE:"hardware-store.png",
        RED_BUTTON:"traffic-puzzle-trigger.png",
        COUNTER:"counter.png",
        BIN:"bin.png"
    },
    
    TRAFFIC_PUZZLE: {
        GROUND:"road.png",
        BLACK_CAR:"big-car.png",
        YELLOW_CAR:"front-car-1.png",
        LONG_TRUCK:"long-truck.png",
        ORANGE_CAR:"front-car-2.png",
        BLUE_CAR:"front-car-3.png",
        RED_CAR:"back-car-2.png",
        AMBULANCE:"ambulance.png",
        LIGHTBLUE_CAR:"back-car-3.png",
        PUZZLE_BORDER:"puzzle-border.png",
        BUTTON_ICON:"button_icon_puzzle.png",
        ICON_CROSS:"icon-cross_puzzle.png"
    },

    BUY: {
      SAW:"Saw.png",
      GLOVES:"Gloves.png",
      PAINT_BRUSH:"Paint Brush.png",
      SCREW_DRIVER:"Screw Divier.png",
      SHOVEL:"Shovel.png",
      SPANNER:"Spanner.png",
      TROWEL:"Trowel.png",
      BUY:"buy.png",
      COIN:"coin.png",
      SHOP_BORDER:"shop-border2.png"
    },
    BUILD: {
        STAIRCASE_ICON:"icon-ladder.png",
        WATER_ICON:"icon-water-tile.png",
        GREEN_ICON:"icon-green-ground-tile.png",
        BROWN_ICON:"icon-brown-ground-tile.png",
        STONE_ICON:"icon-stone.png",
        CEMENT_ICON:"cement-block.png",
        FOUNDATION_ICON:"icon-foundation-blocks.png",

        STAIRCASE_TILE:"tile-ladder.png",
        WATER_TILE:"tile-water.png",
        GREEN_TILE:"tile-green.png",
        BROWN_TILE:"tile-brown.png",
        STONE_TILE:"tile-stone.png",
        CEMENT_TILE:"cement-block.png",
        FOUNDATION_TILE:"tile-foundation-blocks.png",

        CELL_HIGHLIGHT: "cell-highlight.png",
        CLOSE: "close.png",
        SIDE_PANEL: "side-panel.png",
        LETS_BUILD: "lets-build.png",
        BIN_ICON: "icon-delete.png",
        LOCK:"lock.png",
        CROSS_ICON_BUTTON:"button_icon.png",
        
    },

    LEVEL1_WHITELINING: {
        BIG_GROUND:"big ground.png",
        WHITELINE:"whiteline.png",
        "1":"1.png",
        "2":"2.png",
        "3":"3.png",
        "7":"7.png",
        "10":"10.png",
        BUSH:"bush.png",
        BRICKS:"ca-bricks-2.png",
        DUSTBIN:"ca-dustbin.png",
        LADDER:"ca-ladder 1.png",
        PIT:"ca-pit-1.png",
        SEPARATOR:"ca-separator-3.png",
        SIGN:"ca-sign 1.png",
        STEEL_BLOCKS:"ca-steel-blocks.png",
        ELECTRICITY_POLES:"Electricity Poles.png",
        ELECTRICITY: "Electricty.png",
        HOUSE:"House.png",
        HOUSE2:"House 2.png",
        HOUSE3:"House 3.png",
        HOUSE_BOTTOM_2:"house copy 2.png",
        HOUSE_BOTTOM:"house copy.png",
        POT:"pot.png",
        RAILING:"Railing.png",
        HOUSE_UPPER:"Upper right buildings.png",
        UPPER_RIGHT_GRASS:"Upper right grass.png",
        WATER_FOUNTAIN:"water-fountain.png",
        WOODEN_PLANK:"wooden-plank.png",
        STREET_LIGHT:"streelight.png"
 
    },

    LEVEL1_WHITELINING_V2: {
        DRONE:"drone.png",
        FLAG_BLUE:"flag-blue.png",
        FLAG_GREEN:"flag-green.png",
        FLAG_ORANGE:"flag-orange.png",
        FLAG_RED:"flag-red.png",
        FLAG_YELLOW:"flag-yellow.png",
        TV:"TV.png",
        PIPE_ARRANGEMENT:"Pipe Arrangement.png",
        ARROW:"arrowWhitelining.png",
        GREEN_PIPE:"green-pipe.png",
        ORANGE_PIPE:"orange-pipe.png",
        BLUE_PIPE:"blue-pipe.png",
        YELLOW_PIPE:"yellow-pipe.png",
        RED_PIPE:"red-pipe.png",
        WHITE_SQUARE:"whiteSquare.png"
    },

    LEVEL1_WHITELINING_V3: {
        LEFT_UP:"Edge-2-side-rounded.png",
        TOP:"Edge-tile.png",
        NORMAL:"Normal-tile.png",
        LEFT_DOWN:"Normal-2-side-rounded.png",
        SINGLE:"Single.png",
        UP:"Edge-top-1-side-rounded.png",
        DOWN:"Normal-1-side-rounded.png",
        RIGHT:"Edge-1-side-rounded.png",
        
        EXCAVATOR_BACK:"excavator-back.png",
        KEY:"key.png",
        SHOVEL:"shovel.png"
        //BOT:""
       // RIGHT_UP:"right-up.png"
    },

    SKATEPARK_BUILD_SCENE: {
     

        BASE:"base.png",
        BLACK_PARITION_1:"Black-partition-1.png",
        BLACK_PARITION_2:"Black-partition-2.png",
        BLACK_PARITION_3:"Black-partition-3.png",
        BLACK_PARITION_4:"Black-partition-4.png",
        BLACK_PARITION_5:"Black-partition-5.png",
        BLACK_PARITION_6:"Black-partition-6.png",
        BLACK_PARITION_7:"Black-partition-normal.png",
        BUILDING:"building.png",
        DECORATIONS:"decorations.png",
        ENTRANCE_STAIRS:"entrance-stairs.png",
        GARDEN:"garden.png",
        LAMP:"lamp.png",
        MAIN_AREA:"Main-area.png",
        MIDDLE_U:"middle-u.png",
        PARTITION_LEFT_RIGHT_END:"partition-left-right-end.png",
        SIDE_S:"side-s.png",
        WALL:"wall.png",
        VERT_WALL:"vert-wall.png"
    },

    SKATEPARK_BUILD_SCENE_ICONS: {
        UI_BASE:"ui-base.png",
        UI_BUILDING:"ui-building.png",
        UI_DECORATIONS:"ui-decorations.png",
        UI_ENTRANCE_STAIRS:"ui-entrance-stairs.png",
        UI_GARDEN:"ui-garden.png",
        UI_MAIN_AREA:"ui-main-area.png",
        UI_MIDDLE_U:"ui-middle-u.png",
        UI_PARITION:"ui-parition.png",
        UI_WALL:"ui-wall.png",
        UI_SIDE_S:"ui-side-s.png",
        UI_LAMP:"lamp.png",
        UI_VERT_WALL:"ui-vert-wall.png"
    },

    KANSAS_APP: {
        BUTTON:"button.png",
        CHECKMARK:"checkmark.png",
        CIRCLE:"circle.png",
        GREEN_BG:"green-bg.png",
        MAP:"map.png",
        PLAYER_LOCATION:"player-location.png",
        POP_UP_MOBILE:"pop-up-mobile.png",
        LOGO:"logo.png",
        WHITE_BG:"whiteBG.png"
    },

    PIPES: {
        B_H_V:"b_h_v.png",
        B_V:"b_v.png",
        B_V_H:"b_v_h.png",
        G_CROSS_O:"g_cross_o.png",
        G_CROSS_Y:"g_cross_y.png",
        G_H:"g_h.png",
        G_H_V:"g_h_v.png",
        G_V:"g_v.png",
        G_V_H:"g_v_h.png",
        O_CROSS_B:"o_cross_b.png",
        O_H:"o_h.png",
        R_CROSS_O:"r_cross_o.png",
        R_CROSS_Y:"r_cross_y.png",
        R_V:"r_v.png",
        Y_CROSS_B:"y_cross_b.png",
        Y_H:"y_h.png",
        Y_H_V:"y_h_v.png",
        Y_V:"y_v.png",
        Y_V_H:"y_v_h.png",
        N:"n.png"
    },

    CHECKLIST: {
        CHECKBOX: "checkbox.png",
        BUTTON_ICON: "button_icon.png",
        ICON_CROSS: "icon-cross.png",
        ICON_ARROW: "icon-arrow.png",
        FRAME: "frame.png",
        GREEN_HIGHLIGHT: "green-highlight.png",
        INFO_BUTTON: "info.png",
        POPUP: "Pop-up.png",
        TICK_MARK: "tickmark.png",
        GRAY_TITLE: "gray-title.png",
        UNDERLINE: "underline.png",
    },
    PROFILE:{
        coin : "coin.png",
        coinPanel : "coinHUD.png"
    },
    MAP: {
        POPUP: "MAP_Popup.png",
        MAP_SCROLL: "map_scroll.png",
        MAP_SCROLL_HANDLE: "map-scroll-handle.png",
        PROLOGUE_MAP: "map-with-content.png",
        PLAYER_POINT: "Mark_Player.png",
        SO_POINT: "Mark_SO.png",
        MAP2:"Map2.png",
        MAP3:"Map3.png",
        MAP4:"Map4.png",
    },
    PLANT_SPINE: {
        KEY: "ProloguePlant",
        SKIN: {
            Back_Tree_1: "Trees/Back_Tree_1",
            Back_Tree_2: "Trees/Back_Tree_2",
            Bricks_Tree: "Trees/Bricks_Tree",
            Bush: "Bushes/Bush",
            Bush_Blue_Flowers: "Bushes/Bush_Blue_Flowers",
            Bush_Dark: "Bushes/Bush_Dark",
            Bush_Long_Leaves: "Bushes/Bush_Long_Leaves",
            Bush_PetStore: "Bushes/Bush_PetStore",
            Bush_Pink_Flower: "Bushes/Bush_Pink_Flower",
            Bush_Red_Flower: "Bushes/Bush_Red_Flower",
            Bush_Round: "Bushes/Bush_Round",
            Combine: "Bushes/Combine",
            Coconut_Tree: "Trees/Coconut_Tree",
            Color_Leaves_1: "Bushes/Color_Leaves_1",
            Color_Leaves_2: "Bushes/Color_Leaves_2",
            Flower_Blue_2: "Flowers/Flower_Blue_2",
            Flower_Bricks_Blue: "Flowers/Flower_Bricks_Blue",
            Flower_Bricks_Red: "Flowers/Flower_Bricks_Red",
            Flower_Bricks_Yellow: "Flowers/Flower_Bricks_Yellow",
            Flower_Hibiscus_Pink: "Flowers/Flower_Hibiscus_Pink",
            Flower_Hibiscus_Purple: "Flowers/Flower_Hibiscus_Purple",
            Flower_Pink_2: "Flowers/Flower_Pink_2",
            Flower_Pink_3: "Flowers/Flower_Pink_3",
            Flower_Purple_2: "Flowers/Flower_Purple_2",
            Flower_Purple_3: "Flowers/Flower_Purple_3",
            Flower_Red_2: "Flowers/Flower_Red_2",
            Flower_Red_3: "Flowers/Flower_Red_3",
            Leaves_Pot: "Pots/Leaves_Pot",
            Long_Leaves_Pot: "Pots/Long_Leaves_Pot",
            Music_Pot: "Pots/Music_Pot",
            Orange_Pot: "Pots/Orange_Pot",
            Pink_Pot: "Pots/Pink_Pot",
            Purple_Tree: "Trees/Purple_Tree",
            Red_Pot: "Pots/Red_Pot",
            Small_Tree_1: "Trees/Small_Tree_1",
            Small_Tree_2: "Trees/Small_Tree_2",
            White_Pot: "Pots/White_Pot",
            Yellow_Pot: "Pots/Yellow_Pot"
        },
        ANIM: {
            Plants: "Plants",
            Trees: "Trees"
        }
    },
    LEVEL1_OFFICE_SPINE: {
        KEY: "Level1Spine",
        SKIN: {
           SMALL_POT: "Pot"
        },
        ANIM: {
            Idle: "Idle"
        }
    },

    LEVEL1_DUNGEON_SPINE: {
        KEY: "Level1Spine",
        SKIN: {
          ROCKS_1: "Rocks",
          BUCKET: "Bucket",
          RAIL: "Rail"
        },
        ANIM: {
          ROCKS_FALLING: "rocks-falling",
          BUCKET_MOVE: "common-idle",
          RAIL: "rail-idle"
        },
    },

    LEVEL1_DUNGEON_GEM_SPINE: {
        KEY: "Level1DungeonGemSpine",
        SKIN: {
            BLUE_GEM:"Blue Gem",
            COIN1: "Coin 1",
            COIN2: "Coin 2",
            COIN_PILE1: "Coin Pile 1",
            COIN_PILE2: "Coin Pile 2",
            DARK_PURPLE_GEM: "Dark Purple Gem",
            GREEN_GEM: "Green Gem",
            PURPLE_GEM:"Purple Gem",
            RED_GEM:"Red Gem",
            LAMP:"Lamp"
        },
        ANIM: {
            IDLE:"idle"
        },
    },

    LEVEL1_DUNGEON_POND_SPINE: {
        KEY: "Level1Spine",
        KEY2:"Level1DungeonPondSpine",
        SKIN: {
            POND:"Pond",
            FROG:"default",
        },
        ANIM: {
            IDLE:"pond-idle",
            FROG_IDLE:"idle",
            FROG_HINT:"hint-bubble",
            POND_FILLING:"pond-filling",
            POND_EMPTY:"pond-empty"
        },
    },
    LEVEL1_DUNGEON_RIVER_SPINE: {
        KEY:"Level1DungeonRiverSpine",
        SKIN: {
            RIVER:"River",
            CROCODILE:"crocodile",
            ROCK:"Ston"
        },
        ANIM: {
            STONE_IDLE:"river-stone-idle",
            CROCODILE_IDLE:"crocodile-idle",
            CROCODILE_HIT:"crocodile-hit",
            STONE_SINK:"stone-sink"
        },
    },
    LEVEL1_DUNGEON_HAT_PUZZLE_SPINE: {
        KEY_MACHINE:"Level1DungeonHatPuzzleMachineSpine",
        KEY_HAT:"Level1DungeonHatPuzzleHatSpine",
        SKIN: {
            HAT_MACHINE: "default"
        },
        ANIM: {
            CONVEYOR_IN: "conveyor-in",
            MACHINE_ON: "machine-on",
            DEFAULT:"default"
        },
    },
    LEVEL1_EYEWEAR_SPINE: {
        KEY:"Level1EyewearSpine",
        SKIN: {
            AMBULANCE:"ambulance"
        },
        ANIM: {
            AMBULANCE_MOVING:"ambulance-moving"
        },
    },

    LEVEL1_WHITELINING_SPINE: {
        KEY:"Level1ExcavatorSpine",
        KEY2:"Level1BulldozerSpine",
        KEY3:"Level1SoilSpine",
        SKIN: {
            EXCAVATOR:"default",
            BULLDOZER:"default",
            SOIL:"default"
        },
        ANIM: {
            EXCAVATOR_IDLE:"Idle",
            EXCAVATOR_MOVING:"Driving_ahead",
            EXCAVATOR_DIGGING:"Digging",
            BULLDOZER_MOVING:"Driving",
            SOIL_ANIMATION:"animation"
        }
    },
    BUILDING_SPINE: {
        KEY: "PrologueBuilding",
        SKIN: {
            BurgerHouse: "Burger_House",
            ChineseStall: "Chinese_Stall",
            FoodStall: "Food_Stall",
            House: "House",
            IcecreamStore: "Icecream_Store",
            MusicStore: "Music_Store",
            PetStore: "Pet_Store",
            Truck: "Truck",
            Construction: "Construction"
        },
        ANIM: {
            BurgerIcecreamPet: "Burger_Icecream_Pet",
            ChineseFoodStall: "Chinese_Food_Truck",
            HouseMusicStore: "House_Music_Store"
        }
    },
    GRASS_SPINE: {
        KEY: "GrassSpine",
        SKIN: {
            Grass_1: "Grass_1",
            Grass_2: "Grass_2",
            Grass_3: "Grass_3",
            Grass_4: "Grass_4",
            Grass_5: "Grass_5",
            HouseGrass: "House_Grass",
        },
        ANIM: {
            Grass: "animation"
        }
    },
    CHARACTER_SELECTION_IMAGE: {
        BUTTON_SMALL: "Button_small.png",
        CATEGORY_BOX_SELECTED: "category_box_selected.png",
        CATEGORY_BOX_NORMAL: "category_box.png",
        ITEM_NORMAL: "Item_Box.png",
        ITEM_SELECTED: "Item_Box_Selected.png",
        CATEGORY_HAIR: "category_Hair.png",
        CATEGORY_PPE: "category_PPE.png",
        CATEGORY_SKIN_TONE: "category_SkinTone.png",
        CATEGORY_TOP: "category_Top.png",
        CATEGORY_BOTTOM: "category_Bottom.png",
        GIRL_GLOW: "Girl-Glow.png",
        BOY_GLOW: "Boy-Glow.png",
        SMALL_BUTTON_GLOW: "Button-small-Glow.png",
        TICK_MARK: "Tick-mark.png",
        TOGGLE_BG: "ToggleBG.png",
        TOGGLE_ON: "ToggleOn.png",
        TOGGLE_OFF: "ToggleOff.png",
        BACK_BUTTON: "BackButton.png",
        LOCK: "lock.png"
    },
    SPINE_UI: {
        KEY: "UI",
        SKIN: {
            NAME_POPUP: "Popup_Size_2",
            ITEM_POP_UP: "Popup_Size_1",
            BUTTON_BIG: "Button_Big",
            STAGE: "Stage"
        },
        ANIMATION: {
            POUP_UP_OPEN: "Popup_Open",
            BUTTON_BIG: "Button_Big_Idle",
            BUTTON_BIG_PRESSED: "Button_Big_Pressed",
            STAGE_IDLE: "Stage_Idle"
        }
    },
    HTML: {
        NAME_INPUT: "InputNameForm.html"
    },
    STORAGE_KEY: {
        PLAYER_NAME: "PlayerName",
        CHARATER_GENDER: "CharacterGender",
        BUILDING: "Building",
        COMPLETED_CHECKLIST: "completedchecklist",
        COIN : "Coin",
    },
    EVENT: {
        CONTROL_DOWN: "Control_Down",
        CONTROL_UP: "Control_Up",
        BUILDING_SCENE_STOP: "BuildingSectionStop",
        ON_DRESSUP_BACK: "DressUpBack",
        START_DRESSUP: "StartDressUp",
        SHOW_DIALOG: "ShowDialog",
        HIDE_DIALOG: "HideDialog",
        RESTRAT_SCENE: "RestartScene",
        OPEN_CHECKLIST: "OpenChecklist",
        CLOSE_CHECKLIST: "CloseChecklist",
        SHOW_MAP: "ShowMap",
        HIDE_MAP: "HideMap",
        MAP_FOUND : "MapFound"
    },
    KEY: {
        LEFT: "left",
        DOWN: "down",
        RIGHT: "right",
        UP: "up"
    },
    GENDER: {
        BOY: "Boy",
        GIRL: "Girl"
    },
    BUILDING: {
        SKATEPARK: "Skatepark",
        WATERPARK: "Waterpark",
        AMUSEMENT_PARK: "Amusement Park",
        PET_SHOP: "Pet Shop"
    },
    CHARACTER: {
        PLAYER: "Player",
        SO: "Safety Officer",
        MOTHER: "Mom",
        NARRATOR: "Narrator",
        LOCATOR:"Locator"
    },
    DIALOG: {
        APPROACH: "Approach",
        HINT1: "Hint1",
        HINT2: "Hint2",
        MAP_FOUND: "MapFound",
        FIND_SAFETY_EQUIPMENT: "FindSafetyEquipment"
    },
    REPLACE_WORD_BY: {
        BUILDING_NAME: "<buildingName>"
    },
    PPE_STATUS:{
        COLLETCTED : "Collected",
        NOT_COLLETCTED : "NotCollected",
    }
}

